name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install jupyter-book
        pip install ghp-import
    - name: Build book
      run: |
        cd docs
        jupyter-book build .
        touch _build/html/.nojekyll  # Fügt .nojekyll zur Build-Ausgabe hinzu
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        force_orphan: true  # Erzwingt einen sauberen gh-pages Branch